name: emv_qr_core
description: "EMVCo MPM Parser Interoperability Qr data String"
version: 1.0.0
homepage: https://github.com/jaarse/emv_qr_core

environment:
  sdk: ^3.0.0

dependencies:


dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0